### ISSUE TITLE
Track.js

### ISSUE THREAD

**Issue by carodelafuente** [FlorCal/jammming#2]
A few things to note on this component. 

https://github.com/FlorCal/jammming/blob/master/src/Components/Track/Track.js#L35-L43

1. You want to bind your functions inside your constructor, not in your render function: 
```
  constructor(props) {
    super(props);

    this.addTrack = this.addTrack.bind(this);
    this.removeTrack = this.removeTrack.bind(this);
  }
```

2. Your addTrack and removeTrack are event handlers (re: onClick). They need to be passed the event being handled, therefore each function gets passed the 'event' as a parameter: 
```
  addTrack(event) {
    this.props.onAdd(this.props.track)
  }
```

**Comment by FlorCal** [comment]
1. Binded functions in constructor
2. Passed 'event' as parameter on addTrack and removeTrack
