### ISSUE TITLE
savePlaylist() function

### ISSUE THREAD

**Issue by carodelafuente** [FlorCal/jammming#3]
https://github.com/FlorCal/jammming/blob/master/src/Components/App/App.js#L46-L52

You are on the right track here but you aren't saving the playlist to Spotify. You have to use the Spotify object to be able to send that request: 

`Spotify.savePlaylist(this.state.playlistName, trackURIs)`

**Comment by FlorCal** [comment]
@carodelafuente as per your comment on this issue
d7a59ec57ad81a68a70cdda3eb7123f010339fef

I have corrected and tested. Playlist is being saved on Spotify account.
![screen shot 2018-01-21 at 10 39 48 pm](https://user-images.githubusercontent.com/33837853/35208223-085e9ccc-fefc-11e7-9cac-3dd89f923e62.png)

**Comment by carodelafuente** [comment]
Awesome! And great choice of music too. 😉
