### ISSUE TITLE
Concat method

### ISSUE THREAD

**Issue by carodelafuente** [FlorCal/jammming#4]
https://github.com/FlorCal/jammming/blob/master/src/Components/App/App.js#L32

.concat() is a javascript array method used to merge arrays together. Meaning, it should be used on an array element, which you did do (re: `this.state.playListTracks`). But you're passing in `([track])` which should be assumed is already an array so there is no need for the extra brackets `[]`. Was this throwing you an error? Curious about this.

**Comment by FlorCal** [comment]
track is an object , and concatting appending arrays. i put object track into array and concatenation went as predicted. no error

**Comment by carodelafuente** [comment]
Thanks for clarifying. I thought track was an array in this case 😄
